// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utvkbpdqcrtvlcdmviss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dmticGRxY3J0dmxjZG12aXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDc3NTYsImV4cCI6MjA3NTQ4Mzc1Nn0.aEhazi2znJP-1tcwb_lKo_EQAMRMVqJ5XnRZW1n3TAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});